---
- name: "Start and enable Portsentry"
  register: install_portsentry__service_status
  changed_when: install_portsentry__service_status.state != "started"
  ansible.builtin.service:
    name: "portsentry"
    state: "started"
    enabled: yes

- name: "Restart Portsentry"
  register: install_portsentry__service_status
  changed_when: install_portsentry__service_status.state != "restarted"
  ansible.builtin.service:
    name: "portsentry"
    state: "restarted"
    daemon_reload: true
    enabled: yes