---
- name: "Converge"
  hosts: "cicd-debian-11"
  tasks:

    - name: "Include labocbz.install_portsentry"
      tags:
        - "labocbz.install_portsentry"
      vars:
        install_portsentry__base_addresses: "{{ inv_install_portsentry__base_addresses }}"
        install_portsentry__ignore_addresses: "{{ inv_install_portsentry__ignore_addresses }}"
      ansible.builtin.include_role:
        name: "labocbz.install_portsentry"
